# INFOS PARAMS
label: "HEK293_WT_KO"   # label of the analysis
             
# INPUT & OUTPUT PATH
path_out: "output"     # path to the output directory, if it doesn't exist it will be created 
path_inp: "data"    # path to the directory containg inputs - all input files are relative to this directory
reference : "data/GRCh38_96.fa" # reference squence 
modified_sites: "data/miCLIP_union.bed"   # known modified sites
chr_size: "data/hg38.size" # size of chromosomes
regions: "data/selected_regions.bed"  # set of 5-mer (NNANN) to analyze, if ="", all 5-mers (NNANN) will be considered    
# INPUTS PARAMS
data:
    cond1: ["HEK293T-WT-rep2","HEK293T-WT-rep3"]    # BAM file list of all replicates without the extension .bam for condition1
    cond2: ["HEK293T-KO-rep2","HEK293T-KO-rep3"]   #  BAM file list of all replicates without the extension .bam for condition2

# JACUSA PARAMS
jar : "JACUSA_v2.0.1.jar"    # JACUISA2 JAR file 
jacusa_params:               # add any parameter as the key and set its appropriate value as [key: value].
                             # please use "" if no value is affected to the parameter e.g. -D [D: ""].
             p: 16 
             D: ''
             I: ''
             P1: 'FR-SECONDSTRAND' 
             P2: 'FR-SECONDSTRAND'             
             m: 1 
             q: 1 
             c: 4
             a: 'D,Y'
java_params:
             Xmx20g: ''
             XX:ParallelGCThreads=10: ''

# COMBINATION OF PATTERNS           
pattern_params:       # specify patterns and their combinations to be used, please use "" if no value is affected to the field.
        internal_pattern: "Boulias,Koertel,Koh" # specify the annotation of the set of modified sites to be used for the training 
        external_pattern: ""  # path to an external pattern in case you don't use internal_pattern, else put ""
        combined_patterns: # patterns to combine, add as many combinations as you want as a [key(any name): value (pattern numbers)] combination.
                    pt1: [1,2,4,6]  
                    pt2: [1,2,3,4,6]
