label:                            # label of the analysis

# INPUT & OUTPUT PARAMS
path_out:                         # path to the output directory, if it doesn't exist it will be created 
path_inp:                         # path to the directory containing inputs - all input files are relative to this directory
reference:                        # path to the reference sequence 
modified_sites:                   # path to file containing known modified sites
chr_size:                         # path to file containing the size of chromosomes
regions:                          # path to BED6 file containing a set of 5-mer (NNANN) to analyze on, if =null, all 5-mers (NNANN) will be considered    
data:
    cond1:                        # list of bam file names of all replicates without the extension .bam for condition1
    cond2:                        # list of bam file names of all replicates without the extension .bam for condition2

# JACUSA PARAMS
jar:                              # path to JACUSA2 JAR file 
jacusa_params:                    # add any parameter as a name of the key and set its appropriate value as [key: value]. Please put "null" if no value is assigned to the parameter.
    p: 
    D: ''
    I: ''
    P1: 
    P2: 
    m: 
    q: 
    c: 
    a: 'Y'

# JAVA PARAMS
java_params:
    Xmx20g: ''
    'XX:ParallelGCThreads=10': ''
    
# COMBINATION OF PATTERNS               
pattern_params:                    # specify patterns and their combinations to be used, please put "null" if no value is affected to the field.
    internal_pattern:              # specify the annotation of the set of modified sites to be used as a training set 
    external_pattern:              # path to an external pattern in case you don't use internal_pattern, else put "null"
    combined_patterns:             # patterns to combine, add as many combinations as you want as a [key(any name): value (pattern number)] combination.
        pt1: []
        pt2: []
